### ISSUE TITLE
Option "expire_items_per_iter" does not work

### ISSUE THREAD

**Issue by zhka** [tarantool/memcached#16]
1. I set expire_items_per_iter=1000 and run 
```
$echo "flush_all" | nc 127.0.0.1 11211
OK
``` 
Tarantool removes 50 records per second.
2. I found a typo in init.lua script:
```diff
--- a/memcached/init.lua
+++ b/memcached/init.lua
@@ -236,7 +236,7 @@ local stat_table = {
 local conf_table = {
     readahead            = ffi.C.MEMCACHED_OPT_READAHEAD,
     expire_enabled       = ffi.C.MEMCACHED_OPT_EXPIRE_ENABLED,
-    expire_items_per_item= ffi.C.MEMCACHED_OPT_EXPIRE_COUNT,
+    expire_items_per_iter = ffi.C.MEMCACHED_OPT_EXPIRE_COUNT,
     expire_full_scan_time= ffi.C.MEMCACHED_OPT_EXPIRE_TIME,
     verbosity            = ffi.C.MEMCACHED_OPT_VERBOSITY,
     protocol             = ffi.C.MEMCACHED_OPT_PROTOCOL
``` 
 After fixing tarantool uses 100% CPU and do not remove anything.

**Comment by zhka** [comment]
Why not use truncate() function for "flush_all"?

**Comment by bigbes** [comment]
@zhka we can use truncate when `flush_all` is called without arguments, but it'll be relatively slow, if cache is big. This operation will block Tarantool.
I'll look why it hangs Taratnool tomorrow

**Comment by bigbes** [comment]
@zhka I've applied your patch, but can't reproduce Tarantool's 100% CPU usage. Could you provide me test case?

**Comment by zhka** [comment]
### Configuration
I use tarantool-1.6.7  from this package: http://tarantool.org/dist/master/centos/6/os/x86_64/Packages/tarantool-common-1.6.7-463.noarch.rpm,
tarantool/memcached-0.1.0,
small-1.0.0
on CentOS 6.6 x86_64
Startup config:
```lua
box.cfg{
listen=3301;
background = true;
}
local console = require('console')
console.listen('127.0.0.1:3313')

local memcached = require('memcached')
local instance = memcached.create('test', '0.0.0.0:11211', {expire_enabled = true; expire_items_per_iter=1000; space_name = 'memcached'; verbosity=3})
```
### Test case

*  Start tarantool
*  Load 10000 keys in "memcached"
```bash
$ memcslap --servers=127.0.0.1 --verbose --test=set
	Threads connecting to servers 1
	Took 11.771 seconds to load data
```
*  Check:
```
localhost:3313> box.space.memcached:len{}
---
- 10000
...
```
*  Run "flush_all":
```bash
$ echo "flush_all" | nc 127.0.0.1 11211
OK
```
* After about 4 minutes box.space.memcached:len{} returns 0
* **Patch /usr/share/tarantool/memcached/init.lua**
* Restart tarantool
* Get CPU load:
```bash
$ ps aux | grep tarantool
494      25846 100  1.8 1529920 74496 ?       Rsl  17:41   0:14 tarantool memcached.lua <running>
```
100%!
*  Load 10000 keys in "memcached"
```bash
$ memcslap --servers=127.0.0.1 --verbose --test=set
	Threads connecting to servers 1
	Took 12.914 seconds to load data
```
* Run "flush_all":
```
$ echo "flush_all" | nc 127.0.0.1 11211
OK
```
* After about 4 minutes box.space.memcached:len{} returns 10000

**Comment by bigbes** [comment]
@zhka Thank you! I'll look into it.

**Comment by zhka** [comment]
@bigbes Thank you!
I build a branch "macos-fix". The problem is resolved.

**Comment by bigbes** [comment]
Thank you, sorry for inconvenience.

**Comment by bigbes** [comment]
I'll merge this branch into master, when we'll fix the builds.
