### ISSUE TITLE
Possible memleak

### ISSUE THREAD

**Issue by bigbes** [tarantool/memcached#31]
Victor Luchits, [22 дек. 2016 г., 13:58]: 
https://github.com/tarantool/memcached/commit/c49af598c707f2f0fc57b4018580fffa47853488#diff-cbf39d1ef8e3eb0cf0cfa6bf1d6cea8eR213
```
con.sasl_ctx  = (struct sasl_ctx *)calloc(1, sizeof(struct sasl_ctx));
```
я не нашёл нигде free для этой штуки

**Comment by viciious** [comment]
con.sasl_ctx is also missing NULL check
