### ISSUE TITLE
data corruption on sizes >~80kb

### ISSUE THREAD

**Issue by kokh-an** [tarantool/memcached#71]
I get broken data from memcached tarantool instance if data size > ~80kb

OS: CentOS Linux release 7.9.2009 (Core)
PHP: PHP 7.3.29 (cli) (built: Jun 29 2021 09:30:31) ( NTS ) (REMI)
tarantool from rpm's https://packagecloud.io/tarantool/1_10/el/7/
tarantool-1.10.8.45-1.el7.x86_64
tarantool-memcached-1.0.1.4-1.el7.x86_64

tarantool config:
```
        memtx_memory            = 10000 * 1024 * 1024;
        memtx_max_tuple_size    = 2 * 1024 * 1024;
        readahead               = 1 * 1024 * 1024;
```

test data  is file contain 10  text strings  about 12000 bytes length:
```
1 test  test  test  test  test  ...
1 test  test  test  test  test  ...
3 test  test  test  test  test  ...
4 test  test  test  test  test  ...
... etc ..
```
file readed by script and sent do tarantool memcached. 
after this i read key from memcached and got corrupt data:
```
7 test  test  test  test  test  ...
8 test  test  test  test  test  ...  test tesVALUE test 0 120021
1  test  test  test  test  test  ...
2 test  test  test  test  test  ...
```

size of received data - correct and same as size of send data.
but 8-th string is truncated and after this going first string.

php code for reproduce:
```
#!/bin/php
<?php

$m = new Memcached();
$m->addServer('localhost', 11311);
$value = file_get_contents('./debug.txt');
$m->set("test", "$value", 300);
var_dump($m->get("test"));

?>


```

**Comment by dsamirov** [comment]
Maybe php is the problem. I checked it with python and it works fine.
```python
import pylibmc

mc = pylibmc.Client(["127.0.0.1"], binary=True, behaviors={"tcp_nodelay": True, "ketama": True})

print(mc.get("key"))
```

**Comment by Zeraiz** [comment]
memcached.compression_threshold
helps to reduce the size of the value, maybe the problem is at the network level?

**Comment by AnaNek** [comment]
Unable to reproduce bug

OS: Ubuntu 20.04
PHP: 7.4.3
Tarantool: 1.10
Tarantool-memcached: 1.0.1
memcached.compression_threshold = 2000000

**Comment by Totktonada** [comment]
@kokh-an If you're interested to solve the problem, please, share some inputs how to reproduce it. You can see my attempts above: I can't reproduce the problem with given information.

**Comment by LeonidVas** [comment]
Not reproduced.
